### ISSUE TITLE
remove webadmin for security reasons?

### ISSUE THREAD

**Issue by instantflorian** [WBCE/wbce_tools#1]
I strongly recommend to remove the webadmin script. The thought somebody could copy it to his webspace and forget It there, gives me the creeps. 
Yes, there is a warning in readme.md, but it could be overseen quite simple... and after all, which user really _does_ read readme files?
Although there probably are cases where this script could be quite useful, we should not bring unnecessarily less-professional wbce users into dangerous situations.

**Comment by NorHei** [comment]
Then we need to avoid a tool for resetting passwords, as if you leave it on the server .....
We may not add language file tool , as you can modify the language files whith it(ye.s maybe add some unwated content). Even the theme resetter can cause damage to some extend , if you dont remove it after usage.  Removing it from the devault install absolutely makes sense to me . There is a need for this tools in many situations . Just take a look into the forum of any CMS about :"need help, forgot admin password " or google after : "cannot delete files via ftp". If we dont offer any solution pepole will download something from the web and wonder why they suddenly got malware on their server.
At least for my tools i can guarantee that there is no malware in the Code. Just my 2 Cent.
