### ISSUE TITLE
unblock_source_ip throws error

### ISSUE THREAD

**Issue by instantflorian** [WBCE/wbce_tools#4]
Parse error: syntax error, unexpected 'private' (T_PRIVATE), expecting end of file in /.../unblock_source_ip.php on line 19

The issue appears too (with other line number) when I'm removing the comment at the beginning or move the include config.php anywhere else.

I've currently absolutely no idea what's wrong.

**Comment by instantflorian** [comment]
Hm... it works with the former version, maybe just revert the latest commit?
https://github.com/WBCE/wbce_tools/commit/a8180ac4ee99923ac765338f043a183031a48b38#diff-259f324f71cbcb52825c09fe8bad3ac9

**Comment by mrbaseman** [comment]
die Funktion get_client_ip die ich aus dem [WBCE_cms](https://github.com/WBCE/WBCE_CMS/blob/master/wbce/framework/class.login.php#L252) rüberkopiert habe, ist dort eine private Funktion der Login-Klasse. Die private Deklaration macht natürlich hier außerhalb einer Klasse keinen Sinn. 
Mit https://github.com/WBCE/wbce_tools/commit/f7d883c653f3672a227410eaef79b5c6878d04ae habe ich das rausgeworfen. Damit sollte das Skript hoffentlich wieder funktionieren.

**Comment by instantflorian** [comment]
Nope:
Fatal error: Uncaught Error: Using $this when not in object context in 
/.../unblock_source_ip.php:27 Stack trace: #0 
/users/wbcetest/www/0611/unblock_source_ip.php(40): get_client_ip() #1 
{main} thrown in /.../unblock_source_ip.php on line 27

**Comment by mrbaseman** [comment]
Oops... dann [doch nochmal zurück](https://github.com/WBCE/wbce_tools/commit/b92441318b5b39c5077e3a80042f218ab23bc2e5) und wie [du vorgeschlagen hast](https://github.com/WBCE/wbce_tools/issues/4#issuecomment-506612150) mit https://github.com/WBCE/wbce_tools/commit/2c89b8cbc3389dfde5b2da8f882eaaf0d5bf1604 den Commit https://github.com/WBCE/wbce_tools/commit/d82a9a058dc384071b3b9db6e8941204c20d7d92 zurücknehmen, der uns die ganze Sache eingebracht hat. 

Sonst müsste man gerade die [get_server](https://github.com/WBCE/WBCE_CMS/blob/master/wbce/framework/class.wb.php#L512) Methode auch noch mit raus kopieren... aber das $this muss dann auch weg... dann ist der Code in get_client_ip [hier](https://github.com/WBCE/wbce_tools/blob/master/unblock_source_ip/unblock_source_ip.php#L19) trotzdem anders als [im Core](https://github.com/WBCE/WBCE_CMS/blob/master/wbce/framework/class.login.php#L252)
